config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/welcome", to: "welcome#index"
  get "/articles", to: "articles#index"

  resources :modal_test, only: [:index] do 
    post :send_phone_number, on: :collection
    post :check_confirm_number, on: :collection
    get :phone_number_list, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
end

app/models/confirm_phone_number.rb
class ConfirmPhoneNumber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/modal_test_controller.rb
class ModalTestController < ApplicationController
  def index
  end

  def phone_number_lists 
    @phone_number_lists = PhoneNumberList.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/modal_test_helper.rb
module ModalTestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vegivegi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modal_test/_phone_number_list.html.erb
<tr>
  <td class="center aligned">
    <%= number&.id %>
  </td>
  <td class="center aligned">
    <%= number&.phone %>
  </td>
  <td class="center aligned">
    <%= number&.info_agree %>
  </td>
  <td class="center aligned">
    <%= number&.confirm_number %>
  </td>
  <td class="center aligned">
    <%= number&.confirm_check %>
  </td>
  <td class="center aligned">
    <%= number&.created_at %>
  </td>
</tr>

app/views/modal_test/index.html.erb
<h1>ModalTest</h1>

<button class="button button-black" target="_blank" id="modal-event">
인증번호 받기</button>



<!-- send_confirm_number_modal -->
<div class="ui mini modal" id="send_confirm_number_modal">
  <%= form_with(url: send_phone_number_modal_test_index_path, method: :post) do |f| %>
      <i class="close icon"></i>
      <div class="content">
      <h4>앱설치 및 서비스 신청 안내 메시지로 받기<h4>
      <%= f.text_field :phone, placeholder: "핸드폰 번호" %>
      <p>SMS발송 및 부정이용 방지용으로 휴대전화 번호를 수집하며 목적 달성 후 파기할 예정입니다.
      <%= f.check_box :info_agree %></p>
      <div class="actions">
          <%= f.submit "인증하기", class: "ui yellow ok button", id: "send-confirm-number" %>
      </div>
      </div>
  <% end %>
</div>
<!-- modal end -->
<!-- check_confirm_number_modal -->
<div class="ui mini modal" id="confirm_phone_number_modal">
  <%= form_with(url: check_confirm_number_modal_test_index_path, method: :post, local: true) do |f| %>
      <i class="close icon"></i>
      <div class="content">
      <h4>앱설치 및 서비스 신청 안내 메시지로 받기<h4>
      <%= f.text_field :confirm_number, placeholder: "인증번호", autocomplete:"off" %>
      <div class="actions">
          <%= f.submit "전화번호 인증", class: "ui yellow ok button", id: "confirm-number-done" %>
      </div>
      </div>
  <% end %>
</div>
<!-- modal end -->

<script type="text/javascript">
$(document).ready(function(){
  $('#modal-event').click(function(){
    $('#send_phone_number_modal').modal('show');
  })
});

</script>


<script type="text/javascript">
$(document).ready(function(){
  $('#send-confirm-number').click(function(){
    $('#send_confirm_number_modal').modal('hide');
    $('#confirm_phone_number_modal').modal('show');
  });
})
</script>

app/views/modal_test/phone_number_lists.htmls.erb
<div class="ui seven wide column" style="margin-bottom: 30px;">
  <table class="ui celled table">
    <thead>
      <tr class="center aligned">
        <th>ID</th>
        <th>핸드폰 번호</th>
        <th>개인정보 수집 동의</th>
        <th>전송된 인증번호</th>
        <th>생성 날짜</th>
        <th>인증 여부</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @phone_number_lists.each do |number| %>
      <%= render 'phone_number_list', number: number %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/welcome/index.html.erb
<h2>HOME</h2>
<h4>목적 없는 웹사이트 </h4>
<h4>그냥 내가 만들어보고 싶은거 전부 다 레일즈로 만들어볼 예정 </h4>


<ul>
  <li>
    <%= link_to "모달 인증번호 테스트", modal_test_index_path %>
  </li>
</ul>